### ISSUE TITLE
pip install from PyPI failing

### ISSUE THREAD

**Issue by catherinedevlin** [wroberts/pytimeparse#1]
Installing works fine from the github repo, but I'm getting a failure with pip.

```
(ipy1) {master} ~/sw/pytimeparse$ python --version
Python 2.7.4
(ipy1) {master} ~/sw/pytimeparse$ pip install pytimeparse
Downloading/unpacking pytimeparse
  Downloading pytimeparse-1.0.0.tar.gz
  Running setup.py egg_info for package pytimeparse
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/home/catherine/ve/ipy1/build/pytimeparse/setup.py", line 13, in <module>
    with open('README.rst') as file:
    IOError: [Errno 2] No such file or directory: 'README.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/home/catherine/ve/ipy1/build/pytimeparse/setup.py", line 13, in <module>

    with open('README.rst') as file:

IOError: [Errno 2] No such file or directory: 'README.rst'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/catherine/ve/ipy1/build/pytimeparse
Storing complete log in /tmp/tmpQf_lo8
```

I might be able to look for a fix in a couple days.

**Comment by jaraco** [comment]
I stumbled into this issue today when the pip resolver attempted to build every version of this package and failed when it got to 1.0.0. Since that package probably never worked, would you consider deleting that release or yanking it?

**Comment by wroberts** [comment]
@jaraco 1.0.0 deleted now.
