### ISSUE TITLE
No module named future.builtins

### ISSUE THREAD

**Issue by Sighter** [wroberts/pytimeparse#6]
Hey, nice Module so far. But if i want to use it in a python program i get the following error:

```
Traceback (most recent call last):
    File "./rollup.py", line 13, in <module>
    from repositories.rollout  import RolloutRepository
  File "/vagrant/app/repositories/rollout.py", line 8, in <module>
    from models.rollout import Rollout
  File "/vagrant/app/models/rollout.py", line 5, in <module>
    from pytimeparse.timeparse import timeparse
  File "/usr/local/lib/python2.6/dist-packages/pytimeparse/timeparse.py", line 1, in <module>
    from future.builtins import dict
ImportError: No module named future.builtins
```
I have the following version of python (its an old server :)

```
$ python --version
Python 2.6.6
```

thx in advance and cheers
Sascha

**Comment by wroberts** [comment]
Passing travis tests on py2.7, py3.2, py3.3, py3.4.  Closing.
